### ISSUE TITLE
Failure of assert in cluster_generation>origin

### ISSUE THREAD

**Issue by aeroaks** [LukeMathWalker/ndarray-koans#8]
In the `cluster_generation>origin` file I am using distribution values like `Uniform::new(-100., 100.)`.

I am getting the following error in my console:
```
left  = [0.32655481155046684, -1.1355713536118057], shape=[2], strides=[1], layout=C | F (0x3), const ndim=1
right = [0.0, 0.0], shape=[2], strides=[1], layout=C | F (0x3), const ndim=1

', src\koans/02_cluster_generation/00_origin.rs:67:9
```

I have tried other combinations for distribution like `Uniform::new(-10., 10.)`, `Uniform::new(-50., 50.)` but they throw a similar error. with the `left` values being not `0.0`.

**Comment by LukeMathWalker** [comment]
The issue is indeed with the distribution: as the comment says

```
/// We want our observations to be normally distributed around the origin, the 0 vector
```

Check `StandardNormal` :+1:

**Comment by aeroaks** [comment]
That works, Thanks!
